# Generated by Django 3.2 on 2022-01-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='title',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='articletag',
            name='article',
            field=models.ManyToManyField(related_name='tags', to='articles.Article'),
        ),
    ]
